// Copyright 2026 openduo
// SPDX-License-Identifier: FSL-1.1-Apache-2.0
// Generated by tools/pocket/gen_avatars.py; do not edit.
#pragma once

#include "lvgl.h"

typedef enum {
    POCKET_AVATAR_RECEIVED,
    POCKET_AVATAR_LISTENING,
    POCKET_AVATAR_HEARD,
    POCKET_AVATAR_THINKING,
    POCKET_AVATAR_GENERATING,
    POCKET_AVATAR_REPLY,
    POCKET_AVATAR_DEAF,
    POCKET_AVATAR_SENSESOFF,
    POCKET_AVATAR_OFFLINE,
    POCKET_AVATAR_COUNT,
} pocket_avatar_t;

// Indexed by pocket_avatar_t. Large: 176 px wide; small: 64 px wide.
extern const lv_image_dsc_t *const pocket_avatars_large[POCKET_AVATAR_COUNT];
extern const lv_image_dsc_t *const pocket_avatars_small[POCKET_AVATAR_COUNT];
