// Copyright 2026 openduo
// SPDX-License-Identifier: FSL-1.1-Apache-2.0

// User-facing copy in the two UI languages: POCKET_STR_<ID> is Simplified
// Chinese, POCKET_STR_<ID>_EN English. The phone app picks the language
// (APP_STATE). One string per line, `#define NAME "text"`:
// tools/pocket/render_mockups.py and the glyph coverage check read this file
// directly.
#pragma once

#define POCKET_STR_APP_NAME          "多多随身"
#define POCKET_STR_APP_NAME_EN       "DuoDuo Pocket"
#define POCKET_STR_BOOT              "正在启动…"
#define POCKET_STR_BOOT_EN           "Starting…"

#define POCKET_STR_PAIR_TITLE        "等待配对"
#define POCKET_STR_PAIR_TITLE_EN     "Waiting to pair"
#define POCKET_STR_PAIR_SUB          "在 iPhone 上打开多多随身添加设备"
#define POCKET_STR_PAIR_SUB_EN       "Open DuoDuo Pocket on your iPhone"
#define POCKET_STR_PAIR_CODE_TITLE   "配对码"
#define POCKET_STR_PAIR_CODE_TITLE_EN "Pairing code"
#define POCKET_STR_PAIR_CODE_SUB     "和 iPhone 显示的一致就按 OK"
#define POCKET_STR_PAIR_CODE_SUB_EN  "Press OK if it matches your iPhone"
#define POCKET_STR_PAIR_CODE_HINT    "DOWN 取消"
#define POCKET_STR_PAIR_CODE_HINT_EN "DOWN to cancel"
#define POCKET_STR_PAIR_WAIT         "等待手机确认…"
#define POCKET_STR_PAIR_WAIT_EN      "Waiting for the phone…"

#define POCKET_STR_OFFLINE_TITLE     "手机未连接"
#define POCKET_STR_OFFLINE_TITLE_EN  "Phone not connected"
#define POCKET_STR_OFFLINE_SUB       "打开 App 或靠近手机"
#define POCKET_STR_OFFLINE_SUB_EN    "Open the app or move closer"
#define POCKET_STR_OFFLINE_REFUSED   "刚才没有录音"
#define POCKET_STR_OFFLINE_REFUSED_EN "Nothing was recorded"

#define POCKET_STR_HOME_TITLE        "按住 OK 说话"
#define POCKET_STR_HOME_TITLE_EN     "Hold OK to talk"
#define POCKET_STR_HOME_SUB          "回答会显示在这里"
#define POCKET_STR_HOME_SUB_EN       "Answers appear here"
#define POCKET_STR_HINT_SETTINGS     "长按 UP 打开设置"
#define POCKET_STR_HINT_SETTINGS_EN  "Hold UP for settings"

#define POCKET_STR_REC_TITLE         "在听"
#define POCKET_STR_REC_TITLE_EN      "Listening"
#define POCKET_STR_REC_HINT          "松开 OK 发送"
#define POCKET_STR_REC_HINT_EN       "Release OK to send"

#define POCKET_STR_SENDING_TITLE     "收到，正在发送"
#define POCKET_STR_SENDING_TITLE_EN  "Got it, sending"
// Working state after the transcript, by WORK phase.
#define POCKET_STR_WORK_RECEIVED     "收到了"
#define POCKET_STR_WORK_RECEIVED_EN  "Received"
#define POCKET_STR_WORK_THINKING     "在想"
#define POCKET_STR_WORK_THINKING_EN  "Thinking"
#define POCKET_STR_WORK_TOOL         "在查"
#define POCKET_STR_WORK_TOOL_EN      "Searching"
#define POCKET_STR_YOU_SAID          "你说"
#define POCKET_STR_YOU_SAID_EN       "You said"

#define POCKET_STR_REPLY_NAME        "多多"
#define POCKET_STR_REPLY_NAME_EN     "DuoDuo"
#define POCKET_STR_REPLY_STREAMING   "正在回答…"
#define POCKET_STR_REPLY_STREAMING_EN "Answering…"
#define POCKET_STR_REPLY_MORE        "完整内容在手机上"
#define POCKET_STR_REPLY_MORE_EN     "Full text on your phone"

#define POCKET_STR_EMPTY_TITLE       "没听清"
#define POCKET_STR_EMPTY_TITLE_EN    "Didn't catch that"
#define POCKET_STR_EMPTY_SUB         "再按住 OK 说一次"
#define POCKET_STR_EMPTY_SUB_EN      "Hold OK and say it again"
#define POCKET_STR_ASR_TITLE         "没听清"
#define POCKET_STR_ASR_TITLE_EN      "Didn't catch that"
#define POCKET_STR_ASR_SUB           "识别出错，再说一次"
#define POCKET_STR_ASR_SUB_EN        "Recognition failed, try again"
#define POCKET_STR_SEND_TITLE        "发送失败"
#define POCKET_STR_SEND_TITLE_EN     "Send failed"
#define POCKET_STR_SEND_SUB          "这段话没能送出去"
#define POCKET_STR_SEND_SUB_EN       "This message didn't go out"
#define POCKET_STR_SERVER_TITLE      "服务器连不上"
#define POCKET_STR_SERVER_TITLE_EN   "Server unreachable"
#define POCKET_STR_SERVER_SUB        "这段话没有送到多多"
#define POCKET_STR_SERVER_SUB_EN     "This message didn't reach DuoDuo"
#define POCKET_STR_NOTICE_HINT       "UP / DOWN 返回"
#define POCKET_STR_NOTICE_HINT_EN    "UP / DOWN: back"
#define POCKET_STR_BANNER_SERVER     "服务器连不上"
#define POCKET_STR_BANNER_SERVER_EN  "Server offline"

#define POCKET_STR_PROTO_TITLE       "版本不匹配"
#define POCKET_STR_PROTO_TITLE_EN    "Version mismatch"
#define POCKET_STR_PROTO_SUB         "请更新多多随身 App 或设备固件"
#define POCKET_STR_PROTO_SUB_EN      "Update the app or the firmware"

#define POCKET_STR_SETTINGS_TITLE    "设置"
#define POCKET_STR_SETTINGS_TITLE_EN "Settings"
#define POCKET_STR_SET_PREROLL       "预录音"
#define POCKET_STR_SET_PREROLL_EN    "Pre-roll"
#define POCKET_STR_SET_BRIGHTNESS    "亮度"
#define POCKET_STR_SET_BRIGHTNESS_EN "Brightness"
#define POCKET_STR_SET_SCREEN_OFF    "自动息屏"
#define POCKET_STR_SET_SCREEN_OFF_EN "Screen off"
#define POCKET_STR_SECONDS           "秒"
#define POCKET_STR_SECONDS_EN        "s"
#define POCKET_STR_NEVER             "从不"
#define POCKET_STR_NEVER_EN          "Never"
#define POCKET_STR_SET_DEEP_SLEEP    "自动休眠"
#define POCKET_STR_SET_DEEP_SLEEP_EN "Sleep after"
#define POCKET_STR_MINUTES           "分钟"
#define POCKET_STR_MINUTES_EN        "min"
#define POCKET_STR_HOURS             "小时"
#define POCKET_STR_HOURS_EN          "h"
#define POCKET_STR_SET_ALERT_SCREEN  "新回答亮屏"
#define POCKET_STR_SET_ALERT_SCREEN_EN "Wake on reply"
#define POCKET_STR_SET_ALERT_TONE    "新回答提示音"
#define POCKET_STR_SET_ALERT_TONE_EN "Reply tone"
#define POCKET_STR_SET_REPAIR        "重新配对"
#define POCKET_STR_SET_REPAIR_EN     "Re-pair"
#define POCKET_STR_SET_BACK          "返回"
#define POCKET_STR_SET_BACK_EN       "Back"
#define POCKET_STR_ON                "开"
#define POCKET_STR_ON_EN             "On"
#define POCKET_STR_OFF               "关"
#define POCKET_STR_OFF_EN            "Off"
#define POCKET_STR_SETTINGS_HINT     "OK 选择"
#define POCKET_STR_SETTINGS_HINT_EN  "OK to select"

#define POCKET_STR_REPAIR_TITLE      "重新配对？"
#define POCKET_STR_REPAIR_TITLE_EN   "Re-pair?"
#define POCKET_STR_REPAIR_SUB        "会删除和这部手机的配对。之后先在 iPhone 蓝牙设置里忽略本设备"
#define POCKET_STR_REPAIR_SUB_EN     "This unpairs the phone. Then forget this device in iPhone Bluetooth settings"
#define POCKET_STR_REPAIR_HINT       "OK 确认 · UP 取消"
#define POCKET_STR_REPAIR_HINT_EN    "OK: yes · UP: no"
