#!/usr/bin/env python3
# Copyright 2026 openduo
# SPDX-License-Identifier: FSL-1.1-Apache-2.0
"""Convert the duoduo avatar SVGs into LVGL 9 RGB565 images.

Sources: assets/images/avatar/<state>-dark.svg (copied from the ambient web
avatar set). Each state is rendered at two widths on the dark page colour
(--color-bg #0e0e0d) with rsvg-convert, so no alpha channel is needed, and
written as const lv_image_dsc_t arrays in flash.

Outputs: assets/images/avatar/pocket_avatars.c and pocket_avatars.h (committed)
and PNG previews under tools/pocket/.cache/avatars/ for the mockup renderer.
Needs: rsvg-convert (librsvg) and Pillow.
"""
from __future__ import annotations

import subprocess
import sys
from pathlib import Path

from PIL import Image

REPO = Path(__file__).resolve().parents[2]
SRC = REPO / "assets/images/avatar"
CACHE = REPO / "tools/pocket/.cache/avatars"
BG = "#0e0e0d"

# Order is the C enum order (pocket_avatar_t).
STATES = ["received", "listening", "heard", "thinking", "generating", "reply",
          "deaf", "sensesoff", "offline"]
# Large: state screens; small: the reply header. Widths in px.
SIZES = {"large": 176, "small": 64}

HEADER = """// Copyright 2026 openduo
// SPDX-License-Identifier: FSL-1.1-Apache-2.0
// Generated by tools/pocket/gen_avatars.py; do not edit.
"""


def render(state: str, width: int) -> Image.Image:
    CACHE.mkdir(parents=True, exist_ok=True)
    png = CACHE / f"{state}-{width}.png"
    subprocess.run(["rsvg-convert", "-w", str(width), "-b", BG,
                    str(SRC / f"{state}-dark.svg"), "-o", str(png)], check=True)
    return Image.open(png).convert("RGB")


def rgb565_le(img: Image.Image) -> bytes:
    out = bytearray()
    for r, g, b in img.get_flattened_data():
        v = ((r & 0xF8) << 8) | ((g & 0xFC) << 3) | (b >> 3)
        out += bytes((v & 0xFF, v >> 8))
    return bytes(out)


def main() -> int:
    c = [HEADER, '#include "pocket_avatars.h"\n']
    table: dict[str, list[str]] = {k: [] for k in SIZES}
    for size, width in SIZES.items():
        for state in STATES:
            img = render(state, width)
            w, h = img.size
            data = rgb565_le(img)
            name = f"pocket_avatar_{state}_{size}"
            rows = [", ".join(f"0x{b:02x}" for b in data[i:i + 24])
                    for i in range(0, len(data), 24)]
            c.append(f"\nstatic const uint8_t {name}_map[] = {{\n    "
                     + ",\n    ".join(rows) + "\n};\n")
            c.append(f"""static const lv_image_dsc_t {name} = {{
    .header.magic = LV_IMAGE_HEADER_MAGIC,
    .header.cf = LV_COLOR_FORMAT_RGB565,
    .header.w = {w},
    .header.h = {h},
    .header.stride = {w * 2},
    .data_size = sizeof({name}_map),
    .data = {name}_map,
}};
""")
            table[size].append(f"&{name}")
    for size in SIZES:
        c.append(f"\nconst lv_image_dsc_t *const pocket_avatars_{size}[POCKET_AVATAR_COUNT] = {{\n    "
                 + ",\n    ".join(table[size]) + ",\n};\n")
    (SRC / "pocket_avatars.c").write_text("".join(c), encoding="utf-8")

    enum = ",\n    ".join(f"POCKET_AVATAR_{s.upper()}" for s in STATES)
    h = HEADER + f"""#pragma once

#include "lvgl.h"

typedef enum {{
    {enum},
    POCKET_AVATAR_COUNT,
}} pocket_avatar_t;

// Indexed by pocket_avatar_t. Large: {SIZES['large']} px wide; small: {SIZES['small']} px wide.
extern const lv_image_dsc_t *const pocket_avatars_large[POCKET_AVATAR_COUNT];
extern const lv_image_dsc_t *const pocket_avatars_small[POCKET_AVATAR_COUNT];
"""
    (SRC / "pocket_avatars.h").write_text(h, encoding="utf-8")
    print(f"wrote {len(STATES) * len(SIZES)} images")
    return 0


if __name__ == "__main__":
    sys.exit(main())
