#!/usr/bin/env bash
# Copyright 2026 openduo
# SPDX-License-Identifier: FSL-1.1-Apache-2.0
#
# Regenerate the pocket LVGL bitmap fonts from a pinned Noto Sans SC.
# Needs: curl, shasum, python3, node/npx (lv_font_conv is fetched by npx).
# Outputs (committed): assets/fonts/pocket_cjk_20.c, pocket_digits_44.c.
set -euo pipefail

repo="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/../.." && pwd)"
cache="${repo}/tools/pocket/.cache"
out="${repo}/assets/fonts"

# Noto Sans SC 2.004 (SIL OFL 1.1), Simplified Chinese subset OTF.
font_url="https://github.com/notofonts/noto-cjk/raw/Sans2.004/Sans/SubsetOTF/SC/NotoSansSC-Regular.otf"
font_sha="faa6c9df652116dde789d351359f3d7e5d2285a2b2a1f04a2d7244df706d5ea9"
font="${cache}/NotoSansSC-Regular-2.004.otf"
conv="lv_font_conv@1.5.3"

mkdir -p "${cache}"
if [[ ! -f "${font}" ]]; then
    curl -fsSL -o "${font}.tmp" "${font_url}"
    mv "${font}.tmp" "${font}"
fi
echo "${font_sha}  ${font}" | shasum -a 256 -c -

python3 "${repo}/tools/pocket/gen_charset.py" "${out}/pocket_cjk_charset.txt"
range="$(grep -v '^#' "${out}/pocket_cjk_charset.txt" | paste -sd, -)"

# Reply and UI text: 20 px, 4 bpp, uncompressed (no decoder state in RAM).
npx --yes "${conv}" --font "${font}" --range "${range}" \
    --size 20 --bpp 4 --format lvgl --no-compress \
    --lv-font-name pocket_cjk_20 --lv-include lvgl.h \
    --output "${out}/pocket_cjk_20.c"

# Pairing code: digits only, 44 px.
npx --yes "${conv}" --font "${font}" --symbols "0123456789 " \
    --size 44 --bpp 4 --format lvgl --no-compress \
    --lv-font-name pocket_digits_44 --lv-include lvgl.h \
    --output "${out}/pocket_digits_44.c"

# The converter records its absolute input path and the full range list in a
# header comment; keep the committed files free of machine paths. The glyph
# data keeps the font's licence, so each file gets an OFL header.
for f in "${out}/pocket_cjk_20.c" "${out}/pocket_digits_44.c"; do
    python3 - "$f" <<'PY'
import re, sys
p = sys.argv[1]
s = open(p, encoding="utf-8").read()
s = re.sub(r"\* Opts: .*", "* Opts: generated by tools/pocket/gen_fonts.sh (font: Noto Sans SC 2.004, "
           "see that script for ranges and sizes)", s, count=1)
header = ("// Copyright 2014-2021 Adobe (http://www.adobe.com/), with Reserved Font Name 'Source'.\n"
          "// SPDX-License-Identifier: OFL-1.1\n"
          "// Glyph data converted from Noto Sans SC 2.004; licence: assets/fonts/LICENSE-OFL-1.1.txt\n")
if not s.startswith(header):
    s = header + s
open(p, "w", encoding="utf-8").write(s)
PY
done

python3 "${repo}/tools/pocket/check_glyphs.py" --font-c "${out}/pocket_cjk_20.c" \
    --charset "${out}/pocket_cjk_charset.txt" --source-font "${font}"
